name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: npm install
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      working-directory: client
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}