name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: npm install
      run: npm run build
    - name: Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTACTS }}